### ISSUE TITLE
Icon for Manager

### ISSUE THREAD

**Issue by cheatfreak47** [sonicretro/sonicr-mod-loader#1]
Like I did for SADX, I've made an icon I think fits quite nicely with the Sonic R look, I made it in two colors- Blue and Green. Blue I think looks better, but Green is a color that the menu/UI of Sonic R uses a lot for buttons and things so I figured it was worth a shot too. I made them in full 256x256, but typically mod managers use 128x128 icons iirc, so they should be scaled down nicely- probably.

Here are both of them.
![sonic r mod loader deep blue](https://user-images.githubusercontent.com/7818664/32140797-a193b5f4-bc43-11e7-820f-77ea963e4b9f.png) ![sonic r mod loader green](https://user-images.githubusercontent.com/7818664/32140772-fce9bb3e-bc42-11e7-8edc-4b4f12b77c7c.png)

**Comment by cheatfreak47** [comment]
[icon.zip](https://github.com/sonicretro/sonicr-mod-loader/files/1439741/icon.zip)
Here's the icon in an actual icon.ico- went with the Deep Blue one as well. It's the typical sizes for the mod loader icons (16,24,32,48,64,128)
Feel free to add it whenever you want @MainMemory

**Comment by MainMemory** [comment]
I dunno, I'm not really a fan of the "Sonic's head silhouette" design.

**Comment by fancythedeveloper** [comment]
I like this design actually (especially the blue one), [after converting it from .png to .ico] I have it as the icon of the mod loader for me.

**Comment by cheatfreak47** [comment]
![sonic r mod loader alt](https://user-images.githubusercontent.com/7818664/32914275-00f6676e-cae3-11e7-8cc2-630dfdd51584.png)
