### ISSUE TITLE
Um....

### ISSUE THREAD

**Issue by fancythedeveloper** [sonicretro/sonicr-mod-loader#12]
Is this project still alive? Because it doesn't look so.

**Comment by MainMemory** [comment]
Yes.

**Comment by fancythedeveloper** [comment]
How is it still alive if a commit hasn't been done for 5 months?!

**Comment by cheatfreak47** [comment]
MainMemory works on other things too ya know, Sonic R isn't exactly high priority >_>

**Comment by InvisibleUp** [comment]
That and there's not a whole lot that needs to be added or changed to the mod loader, I don't think? Is there anything you need done with it?

**Comment by MainMemory** [comment]
I do plan on bringing it up to speed with the other four, I just got a bit sidetracked with S&KC stuff.
