### ISSUE TITLE
High Resolution PNG Texture Support

### ISSUE THREAD

**Issue by MainMemory** [sonicretro/sonicr-mod-loader#5]
I'm not exactly sure how to implement it, but it would make graphics mods a lot nicer.

**Comment by MainMemory** [comment]
@InvisibleUp do you have any thoughts on this subject?

**Comment by InvisibleUp** [comment]
Texture loading is handled by the function `D3D_LoadTPageRGB(int TexPage, const char *FilePath)` located (in the 2004 version) at address `00407A00`. This function takes a file path and a texture slot ID. It removes any texture in the given slot already, allocates some memory for the texture, and then reads the given file into the newly allocated memory.

We would need to re-write `D3D_ReadTPageRGB(const char *FilePath, char *Buffer, int BytesPerChannel)` at `00407950` to parse the PNG file at `FilePath` and output it to `Buffer`, which is of size `BytesPerChannel * 3`.

As far as libraries, LodePNG (http://lodev.org/lodepng/) seems like the best solution, as it seems really straightforward to use.

**Comment by MainMemory** [comment]
Well, what about higher resolution textures? Is the game just hardcoded for a specific texture size or is there a way to specify that a certain texture has a given size?

**Comment by InvisibleUp** [comment]
I'm not sure. Every texture in the game is 256x256. (Even the 640x480 screens are just split into 256x256 chunks when loaded.) It might be possible (with great difficulty) to scale that up, but I'm pretty certain that you can't have non-square textures.

**Comment by MainMemory** [comment]
Well really, all we have to do is store the size of the texture somewhere and rewrite the function that converts the buffers into D3D textures to account for the size. That is, outside of anything that might manipulate the buffers in memory, it seems like a couple of texture files get merged into a single texture.

**Comment by MainMemory** [comment]
Actually, for loading PNG files, I'm more accustomed to GDI+, since that's what .NET WinForms programs use by default for graphics. Plus, it supports PNG/GIF/JPG/BMP, if we want to do that.

**Comment by InvisibleUp** [comment]
I'm cool with that. Where do you want to store the textures? In the data folder?

**Comment by MainMemory** [comment]
Yeah, the general idea is that the loader would intercept the texture load function and search for any matching file paths in mods with a PNG/GIF/BMP/whatever extension.

**Comment by MainMemory** [comment]
The latest release implements PNG/GIF/BMP support only for the 256x256 textures, and it doesn't support alternate texture sizes.

**Comment by fancythedeveloper** [comment]
So, texture mods are now possible?

**Comment by MainMemory** [comment]
Texture mods have always been possible by editing the .raw files. There's even a [RAW2BMP](https://github.com/sonicretro/RAW2BMP) program I made to make it easier. This just makes it a bit more convenient by removing a conversion step, and will possibly lead to high resolution texture support in the future.

**Comment by fancythedeveloper** [comment]
Ok, I'll maybe release a test mod to see this in action.

**Comment by fancythedeveloper** [comment]
Also, I have this weird bug where the game screen wouldn't scale to the screen but the textures and such would so it would have some weird results. I'll reinstall the mod loader and see if that fixes the problem.

**Comment by MainMemory** [comment]
Implemented in 0c8aafd70ebb91001a72bb4bd186d28b4558a993.
